server:
  port: 8080
spring:
  application:
    name: caller
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
        # group: testgroup
        cluster-name: SH

## 使用配置定义负载均衡策略
#ribbon:
#  eager-load:
#    enabled: true
#    clients: serverA,serverB
#
##这里使用服务提供者的instanceName
#serverA:
#  ribbon:
#    # 代表Ribbon使用的负载均衡策略
#    NFLoadBalancerRuleClassName: com.zml.ribbonConfig.ChooseFirstRule
#    # 每台服务器最多重试次数，但是首次调用不包括在内， Max number of retries on the same server (excluding the first try)
#    MaxAutoRetries: 1
#    # 最多重试多少台服务器，Max number of next servers to retry (excluding the first server)
#    MaxAutoRetriesNextServer: 1
#    # 无论是请求超时或者socket read timeout都进行重试，Whether all operations can be retried for this client
#    OkToRetryOnAllOperations: true
#    # Interval to refresh the server list from the source
#    ServerListRefreshInterval: 2000
#    # Connect timeout used by Apache HttpClient
#    ConnectTimeout: 3000
#    # Read timeout used by Apache HttpClient
#    ReadTimeout: 3000
#serverB:
#  ribbon:
#    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RandomRule